imports:
    - { resource: parameters.yml }

framework:
    secret: "%secret%"
    translator: { fallback: en }
    default_locale: en
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    templating:
        engines: ['php']
    session:
        handler_id: ~
    test: ~

services:
    kernel.listener.data_analytics_tool_authentication_listener:
        class: Rogers\DataAnalyticsToolBundle\Classes\Authentication\Listener
        arguments:
            - @authentication.service
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }