parameters:
    ioffice_database_driver: "Pdo_Mysql"
    ioffice_database_username: "root"
    ioffice_database_password: "root"
    ioffice_database_hostname: "192.168.0.115"
    ioffice_database_port: "3306"