rogers_data_analytics_tool_dashboard_index:
    path: /
    defaults: {_controller: RogersDataAnalyticsToolBundle:Dashboard:index}

rogers_data_analytics_tool_authentication_check:
    path: /authentication
    defaults: {_controller: RogersDataAnalyticsToolBundle:Authentication:index}

rogers_data_analytics_tool_authentication_login:
    path: /authentication/login
    defaults: {_controller: RogersDataAnalyticsToolBundle:Authentication:login}

rogers_data_analytics_tool_authentication_logout:
    path: /authentication/logout
    defaults: {_controller: RogersDataAnalyticsToolBundle:Authentication:logout}