services:
    zend.db.ioffice.adapter:
        class: Zend\Db\Adapter\Adapter
        arguments:
            options:
                driver: "Pdo_Mysql"
                database: "ioffice_test"
                username: "root"
                password: "root"
                hostname: "192.168.0.115"
                port: "3306"
    user.gateway:
        class: Rogers\DataAnalyticsToolBundle\Classes\User\Gateway
        arguments: ["@zend.db.ioffice.adapter"]
    user.repository:
        class: Rogers\DataAnalyticsToolBundle\Classes\User\Repository
        arguments: ["@user.gateway"]
    authentication.hash.service:
        class: Rogers\DataAnalyticsToolBundle\Classes\Authentication\Hash\Service
    authentication.service:
        class: Rogers\DataAnalyticsToolBundle\Classes\Authentication\Service
        arguments: ["@user.repository", "@authentication.hash.service"]
    test.controller.authentication.helper:
        class: Rogers\DataAnalyticsToolBundle\Classes\Test\Controller\Authentication\Helper