services:
#Application
    app.db.ioffice:
        class: Zend\Db\Adapter\Adapter
        arguments:
            options:
                driver: "%ioffice_database_driver%"
                database: "%ioffice_database_database%"
                username: "%ioffice_database_username%"
                password: "%ioffice_database_password%"
                hostname: "%ioffice_database_hostname%"
                port: "%ioffice_database_port%"
    app.session:
        class: Symfony\Component\HttpFoundation\Session\Session

#User
    user.gateway:
        class: Rogers\DataAnalyticsToolBundle\Classes\User\Gateway
        arguments: ["@app.db.ioffice"]
    user.repository:
        class: Rogers\DataAnalyticsToolBundle\Classes\User\Repository
        arguments: ["@user.gateway"]

#Authentication
    authentication.response.repository:
        class: Rogers\DataAnalyticsToolBundle\Classes\Authentication\Response\Repository
    authentication.hash.service:
        class: Rogers\DataAnalyticsToolBundle\Classes\Authentication\Hash\Service
    authentication.session.service:
        class: Rogers\DataAnalyticsToolBundle\Classes\Authentication\Session\Service
        arguments: ["@app.session"]
    authentication.service:
        class: Rogers\DataAnalyticsToolBundle\Classes\Authentication\Service
        arguments: ["@user.repository", "@authentication.response.repository", "@authentication.hash.service", "@authentication.session.service"]