services:
    user.repository:
        class: Rogers\DataAnalyticsToolBundle\Classes\User\Repository
    authentication.service:
        class: Rogers\DataAnalyticsToolBundle\Classes\Authentication\Service
        arguments: ["@user.repository"]
    test.controller.authentication.helper:
        class: Rogers\DataAnalyticsToolBundle\Classes\Test\Controller\Authentication\Helper